{
    "name": "WATI WhatsApp Connector",
    "version": "19.0.11.0.3",
    "summary": "WATI WhatsApp inbox, templates, no-code automation, OTP Bridge, smart buttons, customer timeline, webhooks and API integration for Odoo",
    "category": "Productivity",
    "author": "Abdulrhman Bazarah",
    "license": "LGPL-3",
    "depends": ["base", "base_setup", "web", "contacts", "base_automation"],
    "data": [
        "security/wati_security.xml",
        "security/ir.model.access.csv",
        "data/wati_ticket_sequence.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_views.xml",
        "views/wati_inbox_templates.xml",
        "views/wati_views.xml",
        "views/wati_webhook_monitor_views.xml",
        "views/wati_webhook_attention_views.xml",
        "views/wati_ticket_views.xml",
        "views/wati_template_views.xml",
        "views/wati_template_designer_views.xml",
        "views/wati_template_variable_save_views.xml",
        "views/wati_automation_views.xml",
        "views/wati_otp_bridge_views.xml",
        "data/wati_otp_menu_visibility.xml",
        "views/wati_smart_button_views.xml",
        "views/wati_smart_button_settings_views.xml",
        "views/wati_universal_timeline_views.xml",
        "views/wati_automation_improvements_views.xml",
        "views/wati_automation_ux_views.xml",
        "views/wati_automation_conditions_views.xml",
        "views/wati_automation_builder_views.xml",
        "views/wati_automation_universal_event_views.xml",
        "views/wati_automation_recipient_views.xml",
        "views/wati_automation_template_mapper_views.xml",
        "views/wati_automation_guard_views.xml",
        "views/wati_automation_studio_views.xml",
        "views/wati_automation_review_views.xml",
        "views/wati_automation_template_contract_views.xml",
        "views/wati_automation_log_experience_views.xml",
        "views/wati_workspace_views.xml",
        "data/wati_menu_structure.xml",
        "data/wati_feature_access_sync.xml",
        "data/wati_template_lifecycle_cron.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "wati_connector/static/src/css/wati_automation_ux.css",
            "wati_connector/static/src/css/wati_automation_builder.css",
            "wati_connector/static/src/css/wati_automation_universal_event.css",
            "wati_connector/static/src/css/wati_automation_recipient.css",
            "wati_connector/static/src/css/wati_automation_template_mapper.css",
            "wati_connector/static/src/css/wati_automation_review.css",
            "wati_connector/static/src/css/wati_template_designer.css",
            "wati_connector/static/src/css/wati_template_builder.css",
            "wati_connector/static/src/css/wati_settings.css",
            "wati_connector/static/src/mini_inbox/mini_inbox.css",
            "wati_connector/static/src/mini_inbox/mini_inbox.js",
            "wati_connector/static/src/mini_inbox/mini_inbox.xml",
            "wati_connector/static/src/automation_studio/automation_studio.css",
            "wati_connector/static/src/automation_studio/automation_studio.js",
            "wati_connector/static/src/automation_studio/automation_studio.xml",
            "wati_connector/static/src/automation_studio/smart_target_field.js",
            "wati_connector/static/src/automation_studio/smart_target_field.xml",
            "wati_connector/static/src/workspace/workspace.css",
            "wati_connector/static/src/workspace/workspace_alerts.css",
            "wati_connector/static/src/workspace/workspace_scroll_fix.css",
            "wati_connector/static/src/workspace/workspace.js",
            "wati_connector/static/src/workspace/workspace.xml",
            "wati_connector/static/src/workspace/workspace_alerts.xml",
            "wati_connector/static/src/workspace/workspace_access.xml"
        ]
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
