{
    "name": "WATI WhatsApp Connector",
    "version": "19.0.10.0.12",
    "summary": "WATI WhatsApp inbox, no-code automation, webhooks and API integration for Odoo",
    "category": "Productivity",
    "author": "Abdulrhman Bazarah",
    "license": "LGPL-3",
    "depends": ["base", "base_setup", "web", "contacts", "base_automation"],
    "data": [
        "security/wati_security.xml",
        "security/ir.model.access.csv",
        "data/wati_ticket_sequence.xml",
        "data/wati_template_parameter_repair.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_views.xml",
        "views/wati_inbox_templates.xml",
        "views/wati_views.xml",
        "views/wati_ticket_views.xml",
        "views/wati_automation_views.xml",
        "views/wati_automation_improvements_views.xml",
        "views/wati_automation_ux_views.xml",
        "views/wati_automation_conditions_views.xml",
        "views/wati_automation_builder_views.xml",
        "views/wati_automation_universal_event_views.xml",
        "views/wati_automation_recipient_views.xml",
        "views/wati_automation_template_mapper_views.xml",
        "views/wati_automation_guard_views.xml",
        "views/wati_automation_studio_views.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "wati_connector/static/src/css/wati_automation_ux.css",
            "wati_connector/static/src/css/wati_automation_builder.css",
            "wati_connector/static/src/css/wati_automation_universal_event.css",
            "wati_connector/static/src/css/wati_automation_recipient.css",
            "wati_connector/static/src/css/wati_automation_template_mapper.css",
            "wati_connector/static/src/mini_inbox/mini_inbox.css",
            "wati_connector/static/src/mini_inbox/mini_inbox.js",
            "wati_connector/static/src/mini_inbox/mini_inbox.xml",
            "wati_connector/static/src/automation_studio/automation_studio.css",
            "wati_connector/static/src/automation_studio/automation_studio.js",
            "wati_connector/static/src/automation_studio/automation_studio.xml",
            "wati_connector/static/src/automation_studio/smart_target_field.js",
            "wati_connector/static/src/automation_studio/smart_target_field.xml",
            "wati_connector/static/src/automation_studio/smart_recipient_field.js",
            "wati_connector/static/src/automation_studio/smart_recipient_field.xml"
        ]
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
